// Generated by https://quicktype.io

export interface Reunion {
    id:          number;
    integrantes: number[];
    nombre:      string;
    fecha:       string;
    hora:        string;
    dueño:       number;
}
